#!/bin/bash

basedir=`dirname "$0"`
case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac
basedir="$basedir/.build"

if [ "$1" == "setup" ]; then
  (cd $basedir && pwd && npm install)
fi

if [ -x "$basedir/node" ]; then
  (cd $basedir && "node"  ".bpm/bpm.js" "$@")
  ret=$?
else
  (cd $basedir && node  ".bpm/bpm.js" "$@")
  ret=$?
fi

if [ "$1" == "setup" ]; then
  (cd $basedir && node "node_modules/grunt-cli/bin/grunt" prebuild)
fi

exit $ret
