#!/bin/bash

basedir=`dirname "$0"`
case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac
basedir="$basedir/.build"

if [ "$1" == "setup" ]; then
  "$basedir/npm" install
fi

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/.bpm/bpm.js" "$@"
  ret=$?
else
  node  "$basedir/.bpm/bpm.js" "$@"
  ret=$?
fi

if [ "$1" == "setup" ]; then
  node "$basedir/node_modules/grunt-cli/bin/grunt" prebuild
fi

exit $ret
