#!/bin/bash
basedir=`dirname "$0"`

case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  ("$basedir/$node" "$basedir/itbldz.js" "build" "$@")
  ret=$?
else
  (node "$basedir/itbldz.js" "build" "$@")
  ret=$?
fi
exit $ret
