#!/bin/bash
pushd ".build"

basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac
basedir="$basedir/.build"

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/grunt-cli/bin/grunt" "$@"
  ret=$?
else
  node  "$basedir/node_modules/grunt-cli/bin/grunt" "$@"
  ret=$?
fi
exit $ret

popd
