#!/bin/bash
basedir=`dirname "$0"`

case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac
basedir="$basedir/.build"

if [ -x "$basedir/node" ]; then
  (cd $basedir && "$node"  "node_modules/grunt-cli/bin/grunt" "$@")
  ret=$?
else
  (cd $basedir && node  "node_modules/grunt-cli/bin/grunt" "$@")
  ret=$?
fi
exit $ret
